"""updated models for bakery and bakedgood

Revision ID: be64d59bf322
Revises: 1a660c242acb
Create Date: 2024-10-03 14:18:12.341695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be64d59bf322'
down_revision = '1a660c242acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baked_goods', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('baked_goods', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('baked_goods', 'bakery_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bakeries', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bakeries', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('baked_goods', 'bakery_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('baked_goods', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('baked_goods', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
